# Generated by Django 4.2.30 on 2026-08-17 15:20

from django.db import migrations, models

import plane.db.models.workspace


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="default_display_properties",
            field=models.JSONField(default=plane.db.models.workspace.get_default_issue_display_properties),
        )
    ]
