# Generated by Django 4.2.30 on 2026-08-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_workspace_default_display_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceuserlink",
            name="is_shared",
            field=models.BooleanField(default=False),
        )
    ]
