# Generated by Django 4.2.30 on 2026-08-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("db", "0124_workspaceuserlink_is_shared"),
    ]

    operations = []
